config/routes.rb
Rails.application.routes.draw do
  get 'main/hello'

  root 'courses#index'
  get 'courses' => "courses#index"

  get 'greeter/hello' => "greeter#hello"

  get 'greeter/goodbye'
end

app/models/coursera.rb
class Coursera
  include HTTParty

  default_options.update(verify: false) # Turn off SSL verification
  base_uri 'https://api.coursera.org/api/catalog.v1/courses'
  default_params fields: "smallIcon,shortDescription", q: "search"
  format :json

  def self.for term
    get("", query: { query: term})["elements"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
  	@search_term = params[:looking_for] || 'programming'
  	@courses = Coursera.for(@search_term)
  end
end

app/controllers/greeter_controller.rb
class GreeterController < ApplicationController
  def hello
  	random_names = ["Rareno Zorro", "Saske Uchiha", "Queen of chicken cutlets", "Nami"]
  	@name = random_names.sample
  	@time = Time.now
  	@times_displayed ||= 0
  	@times_displayed +=  1
  end

  def goodbye
  	random_names = ["Sweat hart!", "Gintama"]
  	@name = random_names.sample
  	@time = Time.now
  	@times_displayed ||=0
  	@times_displayed  +=1
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def hello
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/greeter_helper.rb
module GreeterHelper
	def formated_time(time)
		#time string  in AM/PM formated
		time.strftime("%I:%M%p")
	end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/courses/index.html.erb
<h1>Searching for - <%= @search_term %></h1>
<% if @courses.nil? %>
<p>
    No courses found with relevant information
</p>
<% else %>
<table border="1">
  <tr>
  	<th>Image</th>
  	<th>Name</th>
  	<th>Description</th>
  </tr>
  <% @courses.each do |course| %>
    <tr class=<%= cycle('even', 'odd') %>>
      <td><%= image_tag(course["smallIcon"])%></td>
      <td><%= course["name"] %></td>
      <td><%= course["shortDescription"] %></td>
    </tr>
  <% end %>
</table>
<% end %>

app/views/greeter/goodbye.html.erb
<h1>
	Bye-bye, <%= @name %>
</h1>

<p>
	The time now is <%= formated_time(@time) %>
</p>
<p>
	Displayed <%= @times_displayed %> time(s)
</p>

app/views/greeter/hello.html.erb
<h1>
	Greetins, <%= @name %>
</h1>

<p>
	The time now is <%= formated_time(@time) %>
</p>

<p>
	Times displayed is <%= @times_displayed %>
</p>

<p>
	<%= link_to "Google", "http://google.com" %>
</p>
<p>
	<%= link_to "Goodbye", greeter_goodbye_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyFirstApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/hello.html.erb
<h1>
	Hello! What are you looking for?
</h1>